%%writefile /kaggle/working/DMNSP/configs/class/imagenetR200_20-20.yaml
hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}-${method}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'


class_order: "/kaggle/working/DMNSP/class_orders/imagenetR.yaml"
dataset_root: "/kaggle/working/imagenet-r-split"
# sub_train_path: "dataset_reqs/imagenet100_splits/train_100.txt"
# sub_val_path: "dataset_reqs/imagenet100_splits/val_100.txt"
workdir: ""
log_path: "ImangenetR_ours_metrics.json"
model_name: "ViT-B/16"
prompt_template: "a bad photo of a {}."

batch_size: 32
increment: ${initial_increment}
initial_increment: 20   
task_num: 10 
scenario: "class"
dataset: "imagenetR"

weight_decay: 0.0
l2: 0
ce_method: 0

method: "DMNSP"

lr: 1e-3
ls: 0.0


visual_clsf_lr: 0.0005
visual_clsf_batch_size: 32
visual_clsf_epochs: 3
a: 1
b: 6